config/routes.rb
require "routes_constraints/subdomain"

JetTime::Application.routes.draw do

  devise_for :users,
             :controllers => {
                 :omniauth_callbacks => "users/omniauth_callbacks",
                 :sessions => "sessions",
                 :registrations => "registrations"
             }

  constraints(RoutesConstraints::SiteSubdomain) do
    root :to => "site#index"
  end

  constraints(RoutesConstraints::AdminSubdomain) do
    scope module: "admin" do
      root :to => "dashboards#show"
      resource :settings
      resource :dashboards
    end
  end

  constraints(RoutesConstraints::AccountSubdomain) do
    scope :module => "account" do
      root :to => 'dashboards#show'
      resource :dashboard
      resources :staff
      resources :projects
      resources :timesheets
    end
  end

end

app/views/layouts/account.html.haml
!!!
%html
  %head
    %title JetTime
    %link{rel: "shortcut icon", href: "http://www.jetthoughts.com/images/favicon.ico"}
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" type="text/css" media="all" />
    =# stylesheet_link_tag 'web_app_theme'
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style.css'
    
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} JetTime
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              =link_to(t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :method => :delete)
        #main-navigation
          %ul.wat-cf
            %li{:class => controller.controller_path == 'account/staff' ? 'active' : '' }
              %a{:href => staff_index_path} Staff
            %li{:class => controller.controller_path == 'account/projects' ? 'active' : '' }
              %a{:href => projects_path} Projects
            %li{:class => controller.controller_path == 'account/timesheets' ? 'active' : '' }
              %a{:href => timesheets_path} Timesheets
            
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} JetThoughts.
        #sidebar
          = yield :sidebar
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js",
                           "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js"
  = javascript_include_tag :application
  = yield :javascript

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Admin Panel | JetTime
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style.css'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} Admin Panel
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              = link_to t("web-app-theme.settings", :default => "Settings"), settings_path
            %li
              =link_to(t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :method => :delete)
        #main-navigation
          %ul.wat-cf
            %li{:class => controller.controller_path == 'dashboards' ? 'active' : '' }
              %a{:href => dashboards_path} Dashboards
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} Web App.
        #sidebar
          = yield :sidebar

  = javascript_include_tag :application

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JetTime
    %link{rel: "shortcut icon", href: "http://www.jetthoughts.com/images/favicon.ico"}
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style.css'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} JetTime
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              =link_to(t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path, :method => :delete)
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{ :class => "message #{{:alert=>'error'}[type] || type}" }
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} JetTime.
        #sidebar
          = yield :sidebar
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"
  = javascript_include_tag :application

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title JetTime
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style.css'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} JetTime
        #user-navigation
          %ul.wat-cf
            %li
              =link_to(t("web-app-theme.session", :default => "Sign In"), new_user_session_path)
            %li
              =link_to(t("web-app-theme.registration", :default => "Register"), new_user_registration_path)
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Help")
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{ :class => "message #{{:alert=>'error'}[type] || type}" }
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} JetTime.
        #sidebar
          = yield :sidebar
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"
  = javascript_include_tag :application

app/views/layouts/sessions.html.haml
!!!
%html
  %head
    %title JetTime
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style.css'
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/layouts/site.html.haml
!!!
%html
  %head
    %title JetTime
    = stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/default/style.css'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} JetTime
        #user-navigation
          %ul.wat-cf
            %li
              =link_to(t("web-app-theme.registration", :default => "Register"), new_user_registration_path)
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Help")
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{ :class => "message #{{:alert=>'error'}[type] || type}" }
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} JetTime.
        #sidebar
          = yield :sidebar
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"
  = javascript_include_tag :application